
# Site settings
title: OpenShift Workshops
email: example@email.com
description: > # this means to ignore newlines until "baseurl:"
  Create, discover, and download content for your OpenShift instance
  by Red Hat.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
twitter_username: twitter
github_username:  github

# Build settings
markdown: kramdown

# Exclude files
exclude:
  - README.md
  - vendor
  - config.ru
  - Gemfile

# Enable emoji
gems:
  - jemoji
